routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlayerController;
use App\Http\Controllers\MapsController;


/*Landing page */
Route::get('/', function () {
return view('welcome');});
    
/*Redirect to the form */
Route::get('/new_player', [PlayerController::class, 'newplayer'])->name('new_player');

/* Saving the form */
Route::post('/add_player', [PlayerController::class, 'storeplayer'])->name('store_player');

/* Saving the info of the game2 */
Route::post('/complete_game2', [PlayerController::class, 'complete_game2'])->name('completegame2');

/* Saving the info of the game3 */
Route::post('/complete_game3', [PlayerController::class, 'complete_game3'])->name('completegame3');

/* Saving the info of the game1 */
Route::post('/complete_game1', [PlayerController::class, 'complete_game1'])->name('completegame1');

/* Redirect to the introduction */
Route::get('/introduction/{id}', [MapsController::class, 'introduction'])->name('game_intro');

/* Redirect to the maps */
Route::get('/maps/{id}', [MapsController::class, 'showmaps'])->name('show_maps');

/* Redirect to the game1 */
Route::get('/game1/{id}', [MapsController::class, 'game1'])->name('show_game1');

/* Redirect to the game2 */
Route::get('/game2/{id}', [MapsController::class, 'game2'])->name('show_game2');

/* Redirect to the game3 */
Route::get('/game3/{id}', [MapsController::class, 'game3'])->name('show_game3');

/* Redirect to the home */
Route::get('/home', [MapsController::class, 'landing_page'])->name('landing');

/* Redirect to the gamefinale */
Route::get('/game_boss/{id}', [MapsController::class, 'gameboss'])->name('show_game_boss');

Route::get('/finale/{id}', [MapsController::class, 'finale'])->name('show_finale');

Route::get('/ending/{id}', [MapsController::class, 'end'])->name('show_end');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/game1.blade.php
<x-app-layout>
    <link rel="stylesheet" href="{{ ('../css/game1.css') }}">
    <script src="{{ ('../js/game1/main.js') }}" defer></script>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Freshby - The clock</title>
    </head>
<body>
         
        <form action="{{ route('completegame1') }}" method="POST">
    @csrf
   <input type="hidden" name="game1" id="game1" value="1">
   <input type="hidden" name="id" value="{{ $id }}">
    <button type="submit" class="submit" style="display: none">
        Return to the maps
    </button>
  </form>
  <section class="quizz-wrapper">
        <img id="heure1" src="{{ asset('/storage/images/clock/heure1.png') }}">
		<div class="quizz">
			<div class="card question-wrapper active" data-question="1">
                
				<div class="header">
                    <h1>Guess !</h1>
				</div>
				<div class="question">
					What time is it ?
				</div>
				<div class="answers">
					<a href="#" data-answer="a">12H00</a>
					<a href="#" data-answer="b">10H20</a>
					<a href="#" data-answer="c">15H16</a>
				</div>
			</div>
			<div class="card answer">
				<div class="header"></div>
				<div class="answer"></div>
				<div class="reset"></div>
			</div>
		</div>
	</section>
      
<script>
      let btnAnswers = document.querySelector('.question-wrapper .answers');
let cardAnswer = document.querySelector('.card.answer');
let divReset = document.querySelector('.card.answer .reset');
let submit = document.querySelector('.submit');

btnAnswers.addEventListener('click', function(e){
	e.preventDefault();
	var userAnswer = e.target.getAttribute("data-answer").toLowerCase();
	document.querySelector('.question-wrapper').classList.remove('active');
	cardAnswer.classList.add('active');
	
	switch(userAnswer) {
  case "a":
    updateAnswer(false, "Incorrect, try again.");
    break;
  case "b":
    updateAnswer(true, "Correct ! It is indeed 10H20.");     
    break;
  case "c":
    updateAnswer(false, "Incorrect, try again.");
    break;
  default:
    updateAnswer(false, "Incorrect, try again.");
	} 
});
divReset.addEventListener('click', function(e){
	e.preventDefault();
	cardAnswer.querySelector(".header").innerHTML = "";
	cardAnswer.querySelector(".answer").innerHTML = "";
	cardAnswer.classList.remove('active');
	cardAnswer.classList.remove('false');
	cardAnswer.classList.remove('true');
  divReset.innerHTML = "";
	document.querySelector('.question-wrapper.card').classList.add('active');
})

function updateAnswer(status, bodyMsg){
  if(status === false){
    cardAnswer.classList.add('false');
    cardAnswer.querySelector('.header').append("Incorrect, try again.");
    var response = document.createElement("p");
    var responseText = document.createTextNode(bodyMsg);
    var btnReset = document.createElement("a");
    btnReset.setAttribute('href', '#');
    var btnResetText = document.createTextNode("Try again ?");
    btnReset.appendChild(btnResetText);
    divReset.appendChild(btnReset);
    response.appendChild(responseText);
    cardAnswer.querySelector('.answer').appendChild(response);
  }else{
    cardAnswer.classList.add('true');
    cardAnswer.querySelector('.header').append("Correct ! It is indeed 10H20.");
    submit.style.display = "block";
    var response = document.createElement("p");
    var responseText = document.createTextNode(bodyMsg);
    var congrats = document.createElement("h1");
    var congratsText = document.createTextNode("Congratulations!");
    congrats.appendChild(congratsText);
    response.appendChild(responseText);
    cardAnswer.querySelector('.answer').appendChild(response);
    divReset.innerHTML = "";
    divReset.appendChild(congrats);
  }
}
        </script>
    </body>

    </html>
</x-app-layout>

resources/views/game2.blade.php
<x-app-layout>
  <link rel="stylesheet" href="{{ ('../css/game2.css') }}">
     <script src="{{ ('../js/game2/animals.js') }}" defer></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Freshby - Find the animals</title>
</head>
<body>
   
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <p>Click on the cards to flip them <br> and match the animals !</p>
    <img src="{{ asset('/storage/images/animals/tuto_animals.svg') }}" class='tutorial'>
  </div>
</div>
<div class='board'></div>
<div class='clone' id='board'>
  <div class='face'></div>
  <div class='face'></div>
  <div class='face'></div>
  <div class='face'></div>
  <div class='face'></div>
  <div class='face'></div>
</div>
<div class='overlay hidden'>
  <div class='gameover'>
    {{-- Text variable of the button --}}
    <p id="test1"></p> 
    <button class='reset'>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="747.8 72.3 1008 880" enable-background="new 747.8 72.3 1008 880"><path fill="#fff" d="M1742.2 510l-427.4 427.6-97.4-98.8 261.2-259.8h-718v-138.2h718l-259.8-258.4 97.2-98.6 426.2 426.2z"/></svg>
</button>
    <form action="{{ route('completegame2') }}" method="POST">
        @csrf
      <input type="hidden" name="id" value="{{ $id }}">
        <button class="submit" type="submit" id="submit">
        Enregistrer
        </button>
      </form>
  </div>
  
</div>

</body>
</html>
</x-app-layout>

resources/views/game3.blade.php
<x-app-layout>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ ('../css/game3.css') }}">
    <script src="{{ ('../js/game3/main.js') }}" defer></script>
    <title>Freshby - The calculus castle</title>
</head>
<body>
   <form action="{{ route('completegame3') }}" method="POST">
    @csrf
   <input type="hidden" name="game3" id="game3" value="1">
   <input type="hidden" name="id" value="{{ $id }}">
  <button class="button3" id="button3" type="submit">Return to the map</button> 
  </form>
    </br><center><div class="container" id="container">
<img src="{{ asset('/storage/images/castle.png')}}" id="background">
<div class = "cloud1" id = "cloud1"><div class = "cloud_1" id = "cloud_1">
  <div id = cloud1Shadow>
    <div id = "circle1Shadow"></div><div id = "circle2Shadow"></div>
    <div id = "circle3Shadow"></div><div id = "circle4Shadow"></div>
    <div id = "rectShadow"></div>
  </div>
    <div id = "circle1"></div><div id = "circle2"></div>
    <div id = "circle3"></div><div id = "circle4"></div>
    <div id = "rect"></div>
    <div id = "text1">5+7+9</div></div></div>

<div class = "cloud2" id = "cloud2"><div class = "cloud_2" id = "cloud_2">
  <div id = cloud2Shadow>
    <div id = "circle1Shadow_2"></div><div id = "circle2Shadow_2"></div>
    <div id = "circle3Shadow_2"></div><div id = "circle4Shadow_2"></div>
    <div id = "rectShadow_2"></div>
  </div>
    <div id = "circle1_2"></div><div id = "circle2_2"></div>
    <div id = "circle3_2"></div><div id = "circle4_2"></div>
    <div id = "rect_2"></div>
    <div id = "text2">2+2+7+9</div></div></div>
  
 <input id="input1" type="text" size="15" oninput="validateInput(this)" maxlength="10" onkeydown = "if (event.keyCode == 13)
                        document.getElementById('button1').click()"/>
   
<span class="button1" id="button1" style="box-shadow: 0px 1px 0px 0px rgb(187, 218, 247) inset; background: rgb(103, 208, 246) linear-gradient(to bottom, rgb(103, 208, 246) 5%, rgb(61, 153, 184) 100%) repeat scroll 0% 0%; border-radius: 9px; display: inline-block; cursor: pointer; color: rgb(255, 255, 255); font-family: Verdana; font-size: 14pt; padding: 6px 24px; text-decoration: none; text-shadow: 0px 1px 0px rgb(60, 143, 173);" onclick="submit()">Submit</span>  
  
<div id = "score">Score: 0</div>  
  

  
<span class="button2" id="button2" onclick="start(), focusMethod()">Start game</span> 


<div id = "gameOver">Game over! Your score is 0 :)</div>  
   
</div>
  
</center>

</body>
</html>
</x-app-layout>
<script>
  // When the user click on the button it make the focus into the input
  focusMethod = function getFocus() {
  document.getElementById("input1").focus();
  $("#formToDisable :input").prop("disabled", true);
  FocusForced = true;
  // Even listener that if the user is leaving the input then it will put back the focus into the input
document.getElementById("input1").addEventListener("focusout", function() {
          if (FocusForced == true){
            setTimeout(() => {
              document.getElementById("input1").focus();
            }, 100);
          }
        });
        }
</script>

resources/views/game_boss.blade.php
s<x-app-layout>
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Freshby - Boss</title>
  <link rel="stylesheet" href="{{ ('../css/boss.css') }}">
<script src='https://unpkg.com/three@0.123.0/build/three.min.js'></script>
<script src='https://unpkg.com/three@0.123.0/examples/js/loaders/GLTFLoader.js'></script><script  src="./script.js"></script>
</head>
<body>
  <div class="widget-wrap">
  <h1>The final Quizz</h1>
  <div id="quizWrap"></div>
    <div id="code-boxx">
      <a href="" id="ending">Try again</span>
      <a href="{{ route('show_finale', ['id'=>$player->id ]) }}" id="starting">Finish the game !</a>
    </div>
</div>

<div id="canvas"></div>
</body>
</html>
<script>
  
    let scene,
  camera,
  fieldOfView,
  aspectRatio,
  nearPlane,
  farPlane,
  renderer,
  container,
  rocket,
  mixer,
  HEIGHT,
  WIDTH;

const createScene = () => {
  HEIGHT = window.innerHeight;
  WIDTH = window.innerWidth;

  scene = new THREE.Scene();

  scene.fog = new THREE.Fog(0x5d0361, 10, 1500);

  aspectRatio = WIDTH / HEIGHT;
  fieldOfView = 60;
  nearPlane = 1;
  farPlane = 10000;
  camera = new THREE.PerspectiveCamera(
    fieldOfView,
    aspectRatio,
    nearPlane,
    farPlane
  );

  camera.position.x = 0;
  camera.position.z = 500;
  camera.position.y = 50;

  renderer = new THREE.WebGLRenderer({
    alpha: true,
    antialias: true
  });
  renderer.setSize(WIDTH, HEIGHT);

  renderer.shadowMap.enabled = true;

  container = document.getElementById("canvas");
  container.appendChild(renderer.domElement);

  window.addEventListener("resize", handleWindowResize, false);

  let loader = new THREE.GLTFLoader();
    
              loader.load("{{ asset('/storage/3d_objects/boss/scene.gltf') }}", function(gltf){
              const forest = gltf.scene.children[0];
              //Scale the object
              forest.scale.set(80,80,80);
              //Position of the object
              forest.position.set(0,-10,0);
              //Rotation of the object (radian)
              forest.rotation.z=(-4.71);
              scene.add(gltf.scene);
              mixer = new THREE.AnimationMixer(gltf.scene);
               const clips = gltf.animations;
               const clip = THREE.AnimationClip.findByName(clips, 'Walkcycle_Animation');
               const action = mixer.clipAction(clip);
               action.play();
               animate();
               setTimeout(function(){
              animationsecond();
              },5000)
              function animationfirst(){
             
               mixer = new THREE.AnimationMixer(gltf.scene);
               const clips = gltf.animations;
               const clip = THREE.AnimationClip.findByName(clips, 'Walkcycle_Animation');
               const action = mixer.clipAction(clip);
               action.play();
               animate();
                setTimeout(function(){
               animationsecond();
               },5000 )
              }

               function animationsecond(){
              
               mixer = new THREE.AnimationMixer(gltf.scene);
               const clips = gltf.animations;
               const clip = THREE.AnimationClip.findByName(clips, 'Idel_Animation');
               const action = mixer.clipAction(clip);
               action.play();
               animate();
               setTimeout(function(){
               animationfirst();
               },10000 )
              }
              
              
              });
};

const handleWindowResize = () => {
  HEIGHT = window.innerHeight;
  WIDTH = window.innerWidth;
  renderer.setSize(WIDTH, HEIGHT);
  camera.aspect = WIDTH / HEIGHT;
  camera.updateProjectionMatrix();
};

const createLights = () => {
  const ambientLight = new THREE.HemisphereLight(0x404040, 0x404040, 1);

  const directionalLight = new THREE.DirectionalLight(0xdfebff, 1);
  directionalLight.position.set(-300, 0, 600);

  const pointLight = new THREE.PointLight(0xa11148, 2, 1000, 2);
  pointLight.position.set(200, -100, 50);

  scene.add(ambientLight, directionalLight, pointLight);
};

const targetRocketPosition = 40;
const animationDuration = 2000;

const main = () => {
  createScene();
  createLights();
  renderer.render(scene, camera);
 
};

main();
 const clock = new THREE.Clock();
function animate() {

                if(mixer)
                mixer.update(clock.getDelta());
                renderer.render(scene,camera);
                requestAnimationFrame(animate);
             
                }
                animate();
//%ake the smoke of the rocket appear 20 secondes after the user start the page
setTimeout(() => {

 let cam, scene, renderer,
    clock, smokeMaterial,
    h, w,
    smokeParticles = [];

const animate = () => {
        let delta = clock.getDelta();

        requestAnimationFrame(animate);

        [].forEach.call(smokeParticles, sp => {
            sp.rotation.z += delta * 0.2;
        });

        renderer.render(scene, cam);
    },
    resize = () => {
        renderer.setSize(window.innerWidth, window.innerHeight);

    },
    lights = () => {
        const light = new THREE.DirectionalLight(0xcef5c8, 0.5);
        clock = new THREE.Clock();
        renderer = new THREE.WebGLRenderer({
        alpha: true,
        antialias: true
        });
        renderer.setClearColor( 0xffffff, 0);
        renderer.setSize(w, h);

        scene = new THREE.Scene();
        scene.background = new THREE.Color( 0xffffff, 0 );
        light.position.set(-1, 0, 1);
        scene.add(light);
    },
    camera = () => {
        cam = new THREE.PerspectiveCamera(
            75,
            w / h,
            1,
            10000
        );

        cam.position.z = 1000;

        scene.add(cam);
    },
    action = () => {
        const loader = new THREE.TextureLoader();

        loader.crossOrigin = '';

        loader.load(
            'https://s3-us-west-2.amazonaws.com/s.cdpn.io/82015/blue-smoke.png',
            function onLoad(texture) {
                const smokeGeo = new THREE.PlaneBufferGeometry(200, 100);

                smokeMaterial = new THREE.MeshLambertMaterial({
                    map: texture,
                    transparent: true
                });

                for (let p = 0, l = 350; p < l; p++) {
                    let particle = new THREE.Mesh(smokeGeo, smokeMaterial);

                    particle.position.set(
                        Math.random() * 400 - 250,
                        Math.random() * 400 - 250,
                        Math.random() * 900 - 100
                    );

                    particle.rotation.z = Math.random() * 200;
                    scene.add(particle);
                    smokeParticles.push(particle);
                }
                  const spaceTexture = new THREE.TextureLoader().load("{{ asset('/storage/images/apocalypse.jpg') }}");
            scene.background = spaceTexture;

                animate();
            }
        );

    },
    init = () => {
        h = window.innerHeight;
        w = window.innerWidth;
        
        lights(); //💡
        camera(); // 🎥
        action(); // 🎬

        document.body.appendChild(renderer.domElement);
        
    };

init();
}, 3000)

    </script>
    <script>
      var quiz = {
  // (A) PROPERTIES
  // (A1) QUESTIONS & ANSWERS
  // Q = QUESTION, O = OPTIONS, A = CORRECT ANSWER
  data: [
  {
    q : "How much is 18+10",
    o : [
      "8",
      "28", //true//
      "21",
      "7"
    ],
    a : 1 // arrays start with 0, so answer is 70 meters
  },
  {
    q : "Which animal does not come from the farm ?",
    o : [
      "Cow",
      "Pig",
      "Chicken",
      "Cheetah" //true//
    ],
    a : 3
  },
  {
    q : "What is the color of a crocodile ?",
    o : [
      "Red",
      "Yellow",
      "Green", //true//
      "Purple"
    ],
    a : 2
  },
  {
    q : "What's the name of your companion ?",
    o : [
      "Mirallia", //True//
      "Mallia",
      "Maria",
      "Maloya"
    ],
    a : 0
  },
  {
    q : "How many hours are there in a day ?",
    o : [
      "10 hours",
      "22 hours",
      "12 hours",
      "24 hours" //true//
    ],
    a : 3
  }
  ],

  // (A2) HTML ELEMENTS
  hWrap: null, // HTML quiz container
  hQn: null, // HTML question wrapper
  hAns: null, // HTML answers wrapper

  // (A3) GAME FLAGS
  now: 0, // current question
  score: 0, // current score

  // (B) INIT QUIZ HTML
  init: () => {
    // (B1) WRAPPER
    quiz.hWrap = document.getElementById("quizWrap");

    // (B2) QUESTIONS SECTION
    quiz.hQn = document.createElement("div");
    quiz.hQn.id = "quizQn";
    quiz.hWrap.appendChild(quiz.hQn);

    // (B3) ANSWERS SECTION
    quiz.hAns = document.createElement("div");
    quiz.hAns.id = "quizAns";
    quiz.hWrap.appendChild(quiz.hAns);

    // (B4) GO!
    quiz.draw();
  },

  // (C) DRAW QUESTION
  draw: () => {
    // (C1) QUESTION
    quiz.hQn.innerHTML = quiz.data[quiz.now].q;

    // (C2) OPTIONS
    quiz.hAns.innerHTML = "";
    for (let i in quiz.data[quiz.now].o) {
      let radio = document.createElement("input");
      radio.type = "radio";
      radio.name = "quiz";
      radio.id = "quizo" + i;
      quiz.hAns.appendChild(radio);
      let label = document.createElement("label");
      label.innerHTML = quiz.data[quiz.now].o[i];
      label.setAttribute("for", "quizo" + i);
      label.dataset.idx = i;
      label.addEventListener("click", () => { quiz.select(label); });
      quiz.hAns.appendChild(label);
    }
  },

  // (D) OPTION SELECTED
  select: (option) => {
    // (D1) DETACH ALL ONCLICK
    let all = quiz.hAns.getElementsByTagName("label");
    for (let label of all) {
      label.removeEventListener("click", quiz.select);
    }

    // (D2) CHECK IF CORRECT
    let correct = option.dataset.idx == quiz.data[quiz.now].a;
    if (correct) {
      quiz.score++;
      option.classList.add("correct");
    } else {
      option.classList.add("wrong");
    }

    // (D3) NEXT QUESTION OR END GAME
    quiz.now++;
    setTimeout(() => {
      if (quiz.now < quiz.data.length) { quiz.draw(); }
      else {
        quiz.hQn.innerHTML = `You have answered ${quiz.score} of ${quiz.data.length} correctly.`;
        quiz.hAns.innerHTML = "";
        if (quiz.score == 5) {
          var ending = document.getElementById("starting");
          ending.style.display = "block";
        }
        else if (quiz.score < 5) {
           var restart = document.getElementById("ending");
           restart.style.display = "block";
           setTimeout(function() {
              restart.style.display = "none";
              quiz.init();
           },2000)
        
        }

      }
      
    }, 1000);
  },

  // (E) RESTART QUIZ
  reset : () => {
    quiz.now = 0;
    quiz.score = 0;
    quiz.draw();
  }
};
window.addEventListener("load", quiz.init);

      </script>
  </x-app-layout>

resources/views/game_finale.blade.php
<x-app-layout>
    <link rel="stylesheet" href="{{ ('../css/finale.css') }}">
    <script src="{{ ('../js/game_finale/main.js') }}" defer></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Freshby - End</title>
</head>
<body>
    <div class="container">
        <span class="text">
            Good job 
            
            ! You have defeated Billytrash and saved the world !<br>
            Now it is time to say goodbye and end this adventure <br>
        </span>
    </div>
    <canvas class="boss"></canvas>
    <script type="module">
   
      import * as THREE from '../three.js-master/src/Three.js';
      import { OrbitControls } from '../three.js-master/examples/jsm/controls/OrbitControls.js';
      import { GLTFLoader } from '../three.js-master/examples/jsm/loaders/GLTFLoader.js';
      import { EffectComposer } from '../three.js-master/examples/jsm/postprocessing/EffectComposer.js';
      import { RenderPass } from '../three.js-master/examples/jsm/postprocessing/RenderPass.js';
      import { GlitchPass } from '../three.js-master/examples/jsm/postprocessing/GlitchPass.js';
      import { ShaderPass } from '../three.js-master/examples/jsm/postprocessing/ShaderPass.js';
      import { LuminosityShader } from '../three.js-master/examples/jsm/shaders/LuminosityShader.js';
     

      let scene, camera, renderer, mixer, controls, composer;

               
         function init() { 

            scene = new THREE.Scene();
            //Set the position of the camera
            camera = new THREE.PerspectiveCamera(40,window.innerWidth/window.innerHeight,1,5000);

            camera.rotation.set(-0.25, -0.10, 0);
            camera.position.x = -33;
            camera.position.y = 80;
            camera.position.z = 300;
            camera.lookAt(0, 0, 0);

            document.body.addEventListener("click",()=>{
                console.log(camera.position, camera.rotation)
            });

            renderer = new THREE.WebGLRenderer({
            canvas: document.querySelector('.boss'),
            });
            // Put the 3d scene into a canvas named "forest"
            renderer.setSize( window.innerWidth, window.innerHeight );
            document.body.appendChild( renderer.domElement );

            // Post processing effect
            composer = new EffectComposer(renderer);
            composer.addPass(new RenderPass(scene, camera));
            animate();
           
            controls = new OrbitControls(camera, renderer.domElement);
            controls.addEventListener('change', renderer);
            controls.update();
            
            //Creating virtual light
            const hlight = new THREE.AmbientLight (0xfcff,0.9);
            scene.add(hlight);

            const directionalLight = new THREE.DirectionalLight(0xffffff,1);
            directionalLight.position.set(0,220,0);
            directionalLight.castShadow = true;
            scene.add(directionalLight);
            const light = new THREE.PointLight(0xfcff,2, 0);
            light.position.set(-10,220,-10);
     
            scene.add(light);
            const light2 = new THREE.PointLight(0xfcff,2, 0);
            light2.position.set(30,220,30);
         
            scene.add(light2);
            const light3 = new THREE.PointLight(0xfcff,2, 0);
            light3.position.set(0,220,0);
            scene.add(light3);

            const light4 = new THREE.PointLight(0xfcff,2, 0);
            light4.position.set(-30,220,-30);
             scene.add(light4);
                       
              // Loader to load my scene
              let loader = new GLTFLoader();
         
              //Choose the files
              loader.load("{{ asset('/storage/3d_objects/finale/scene.gltf') }}", function(gltf){
              const boss = gltf.scene.children[0];
              //Scale the object
              boss.scale.set(3,3,3);
              //Position of the object
              boss.position.set(0,-30,0);
              //Rotation of the object (radian)
              boss.rotation.z=(0);
              scene.add(gltf.scene);
              //Load the animations of my object
              mixer = new THREE.AnimationMixer(gltf.scene);
              const clips = gltf.animations;
              const clip = THREE.AnimationClip.findByName(clips, 'Experiment');
              const action = mixer.clipAction(clip);    
               //Play the action
              action.play();

              animate();
              });
          
            }
            
                //Loop the animation 
                const clock = new THREE.Clock();
                function animate() {

                if(mixer)
                mixer.update(clock.getDelta());
                renderer.render(scene,camera);
                requestAnimationFrame(animate);
                composer.render(scene,camera);

                }
  
           

          init();
          animate();
                redirect();
          function redirect() {
              setTimeout(function(){
                window.location.href = "{{ route('show_end', ['id'=>$player->id]) }}";
              },19000)
          }
    </script> 
</body>
</html>
</x-app-layout>

resources/views/landing_page.blade.php
<x-app-layout>
<link rel="stylesheet" href="{{ ('css/main.css') }}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Freshby - Kids Game</title>
</head>
    <body>
        <div class="play">
            <div class="logo">
                <img src="{{ asset('/storage/images/logo/staff_logo.svg') }}" class="logobutton" id="staff">
                <img src="{{ asset('/storage/images/logo/sword_logo.svg') }}" class="logobutton" id="sword">
            </div>
            <button id="myBtn" class="button">
               <div></div>
            </button>
             <audio src="{{ asset('/storage/audio/bouton.mp3') }}" id="myAudio"></audio>
        </div> 
    </body>
</html>
</x-app-layout>
{{-- Script that play the sound and redirect to the next page--}}
<script>  
    document.getElementById("myBtn").addEventListener("click",function(){
    document.getElementById("myAudio").play();
    setTimeout(() => {
        document.location.href = "{{ route('new_player') }}";
    }, 1000 );
    }
    );
</script>
@include('partials.footer')